builds:
  - id: codeowners-validator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/mszostok/codeowners-validator/pkg/version.version={{.Version}} -X  github.com/mszostok/codeowners-validator/pkg/version.commit={{.ShortCommit}} -X github.com/mszostok/codeowners-validator/pkg/version.buildDate={{.Date}}
    # List of combinations of GOOS + GOARCH + GOARM to ignore.
    # Default is empty.
    ignore:
      - goos: windows # due to upx error: CantPackException: can't pack new-exe
        goarch: arm64
    hooks:
      # Install upx first, https://github.com/upx/upx/releases
      post: upx -9 "{{ .Path }}"

archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

dockers:
  - dockerfile: Dockerfile
    ids:
      - codeowners-validator
    image_templates:
      - "ghcr.io/mszostok/codeowners-validator:stable"
      - "ghcr.io/mszostok/codeowners-validator:{{ .Tag }}"
      - "ghcr.io/mszostok/codeowners-validator:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/mszostok/codeowners-validator:v{{ .Major }}"
      - "mszostok/codeowners-validator:latest"
      - "mszostok/codeowners-validator:{{ .Tag }}"
      - "mszostok/codeowners-validator:v{{ .Major }}.{{ .Minor }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dist: bin

release:
  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: true
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: mszostok
    name: codeowners-validator
