required = [
  "github.com/golang/lint/golint",
  "golang.org/x/tools/cmd/goimports",
]

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/google/go-github"
  version = "21.0.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
