name: Pull request

on:
  pull_request:
    branches: [ master ]

env:
  GO111MODULE: on
  INSTALL_DEPS: true

defaults:
  run:
    shell: bash

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: "Build and unit-test with Go ${{ matrix.go-version }}"
      run: make test-unit
    - name: "Hammer unit-test with ${{ matrix.go-version }}"
      run: make test-hammer
  code-quality-test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.14.x, 1.15.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: "Code Quality Analysis"
        run: make test-lint
  integration-test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - if: matrix.os == 'windows-latest'
        run: echo "BINARY_EXT=.exe" >> $GITHUB_ENV
      - name: "Integration testing with ${{ matrix.go-version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_INTEGRATION_TESTS }}
        run: |
          echo "${{ env.BINARY_PATH }}"
          make test-integration
